<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print $this->render('layout/navigation.phtml');

$badges = array(
	'version'     => $this->getBadge($results['version'], 'PHP '.PHP_VERSION),
	'timeLimit'   => $this->getBadge($results['time_limit']),
	'memLimit'    => $this->getBadge($results['mem_limit']),
	'safeMode'    => $this->getBadge($results['safe_mode'], 'safe_mode'),
	'openBasedir' => $this->getBadge($results['open_basedir'], 'open_basedir')
);

?>
<form class="form-horizontal">
	<fieldset>
		<legend><?php print t('welcome') ?></legend>
		<p><?php print t('intro') ?></p>
	</fieldset>

	<fieldset>
		<legend><?php print t('general_config') ?></legend>

		<div class="control-group">
			<label class="control-label" for="projectName"><?php print t('projectname') ?>:</label>
			<div class="controls">
				<input type="text" id="projectName" name="projectName" value="<?php print sly_html($projectName) ?>" placeholder="Mein Projekt" />
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="timezone"><?php print t('timezone') ?>:</label>
			<div class="controls">
				<input type="text" id="timezone" placeholder="Europe/Berlin" />
			</div>
		</div>

		<div class="control-group">
			<div class="controls">
				<?php print implode("\n", $badges); ?>
			</div>
		</div>

		<div class="control-group">
			<div class="controls">
				<label class="checkbox">
					<input type="checkbox"> <?php print t('read_license') ?>
				</label>
			</div>
		</div>
	</fieldset>

	<fieldset>
		<legend><?php print t('database_access') ?> <span class="pull-right" style="font-size:14px">(<a href="foo">erweiterte Konfiguration anzeigen</a>)</span></legend>

		<div class="control-group">
			<label class="control-label" for="inputPassword">Benutzer &amp; Passwort:</label>
			<div class="controls controls-row">
				<input type="text" id="inputPassword" placeholder="username" class="span3">
				<input type="text" id="inputPassword" placeholder="mypassword" class="span3">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="inputPassword">Datenbank:</label>
			<div class="controls controls-row">
				<input type="text" id="inputPassword" placeholder="mydatabase" class="span3">
				<label class="checkbox span2">
					<input type="checkbox"> anlegen
				</label>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="tablePrefix">Tabellen-Präfix:</label>
			<div class="controls">
				<input type="text" id="tablePrefix" placeholder="sly_" class="span1" title="muss i.d.R. nicht geändert werden; erlaubt es, mehrere Projekte in einer Datenbank zu verwalten" rel="tooltip" data-placement="right" data-trigger="focus" />
			</div>
		</div>

		<div class="control-group" style="display:none">
			<label class="control-label" for="inputEmail">Datenbank-Typ:</label>
			<div class="controls">
				<select title="Alle Datenbanken außer MySQL sind als hoch experimentell anzusehen und dienen zu Testzwecken!" rel="tooltip" data-placement="right" data-trigger="focus">
					<option>MySQL</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				</select>
			</div>
		</div>

		<div class="control-group" style="display:none">
			<label class="control-label" for="inputPassword">Host:</label>
			<div class="controls">
				<input type="text" id="inputPassword" placeholder="localhost">
			</div>
		</div>

		<div class="form-actions">
			<button type="submit" class="btn btn-primary">Zum nächsten Schritt &raquo;</button>
		</div>
	</fieldset>
</form>

<script type="text/javascript">
jQuery('[rel=tooltip]').tooltip();
</script>
