<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

?>
<div class="alert alert-error">
	<h4><?php print sly_html($title) ?></h4>
	<?php print sly_html($message) ?>
</div>

<?php if (!empty($trace)): ?>
<pre class="prescrollable"><?php print sly_html($trace) ?></pre>
<?php endif ?>
