<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<ul class="nav nav-pills" style="margin-left:190px">
	<li class="active"><a href="<?php print $_router->getUrl('index') ?>" data-toggle="tab"><i class="icon-edit"></i> Konfigurieren</a></li>
	<li class="disabled"><a href="">&raquo;</a></li>
	<li class="disabled"><a href="<?php print $_router->getUrl('install') ?>"><i class="icon-wrench"></i> Einrichten</a></li>
	<li class="disabled"><a href="">&raquo;</a></li>
	<li class="active"><a href="#tab3"><i class="icon-heart"></i> Profit!</a></li>
</ul>

<div class="tab-content">
	<div class="tab-pane">
		1
	</div>
</div>
